description: For things learned and thought about while on my journey into becoming a better programmer
repository: tristanburgess/tristanburgess.github.io
theme: jekyll-theme-architect
title: Tristan Burgess's Blog
twitter_url: https://twitter.com/tburgessdev
